parameters:
#    prgmr_bill_rate_my_cat.example.class: PrgmrBill\RateMyCatBundle\Example

services:
#    prgmr_bill_rate_my_cat.example:
#        class: %prgmr_bill_rate_my_cat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
